version: '3'
services:
  backend:
    build: backend
    ports:
     - "8888:8888"
    volumes:
     - ./backend:/code
  frontend:
    build: frontend
    ports:
     - "8889:8889"
    volumes:
     - ./frontend:/code
     - /code/node_modules
